include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    library_private_types_in_public_api: false  # Отключаем правило
    use_build_context_synchronously: false  # Отключаем правило для async gaps

analyzer:
  exclude:
    - lib/app.dart  # Исключаем app.dart от проверки prefer_const_constructors