name: testingplatform
description: A new Flutter project

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  provider: ^6.1.2
  go_router: ^14.3.0
  intl: ^0.19.0

flutter:
  uses-material-design: true